name: Update WHOIS servers list

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2
      
    - name: Git LFS pull
      run: git lfs pull

    - name: Set up Python from Pipfile
      id: python
      run: |
        echo "::set-output name=version::$(grep python_version Pipfile | cut -d'"' -f2)"

    - name: Install pipenv
      run: |
        pip install pipenv

    - name: Install dependencies using Pipenv
      run: |
        cd whois-server-list-generator
        pipenv install

    - name: Generate updated WHOIS server list
      run: |
        cd whois-server-list-generator
        pipenv run python generate_whois_servers.py

    - name: Check for changes in CSV
      run: |
        git diff --exit-code whois-servers.csv || (echo "Changes detected in CSV" && exit 1)

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "Automatically updated on $(date +'%Y-%m-%d')"
        title: "Update WHOIS servers list - $(date +'%Y-%m-%d')"
        branch: "update-whois-list-$(date +'%Y-%m-%d')-${{ github.run_number }}"
        labels: automated-pr

    - name: PR details
      run: |
        echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
        echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
